# borrowed from https://gist.github.com/dan-blanchard/7045057
language: python
sudo: required
dist: trusty 

python:
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-all-dev liblapack-dev libblas-dev
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy matplotlib seaborn pytest pandas freeze 
    - python setup.py -q install

script: py.test baxcat/
