language:
    python

python:
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-all-dev liblapack-dev libblas-dev gfortran 

install:
    - pip install -q cython numpy pytest
    - pip install scipy
    - pip install -q pandas freeze matplotlib seaborn
    - python setup.py -q install

script: py.test baxcat/
